language: node_js
node_js:
  - '9'
install: npm install
script: npm run tsc
deploy:
  provider: npm
  email: l.gholoi@outlook.com
  api_key:
    secure: Ive6vRMse7jznX+zDue+dcEB/PFBQXAy2sTnkBuGC2ghAxnkWvOY1xRSl9RNivulA6DMEr2wAAFuUZJANQPJFQjkngDsAVVdoxtnMMxt6ondu1Am//yQgY0MVWpzq3lQGpEEtbbjhuy2RpXDCF9a+I44/1GiQ9cx5LAV/jEKsQPR7qQMyBR8fxnXBApy2otMOuzhfCZaVlU9e32pejSVr8ECJbrXunMM0fE5J0tj5+uc6llpGeVs3CC84ubj7XNPWavMKa7L3jVFqQt9NJdy8Fh0sp8zWqIpiIxVUbCrdfgRqJkwECQsYlcrASqpYsocTygZj1srg56iCeINeLYaNdEE1nIjTIIPjATdXJvXtiu2Aas0aXqTEBB2EY2Rw0QDYcIdtPpL9vDr9ELZskMXhYzs/itmRrpVHtNSoEMevCSKxeaLE2zGEFhTuMGTmKFNkZqk+32Spxpt0JSvMSczDLlDH9geGlNGuUrlsV5NhXubEj0aEwi670Rs6H4z9Ho+EYeBHvsqg7oSVMAI8JlH16JwDhypyP+DgiHbZBA58mCHtcl8gj001Z+y/HmbOixDdaV6DmgAj8f0b7Z18VfzmAMIOHlrp+jtd2pOTYddaRDxXwPEaG81Sh6S0GftW0lpXQjABJatHNOsdEV9uj13m4x8I/aYNqNgyHRKPC/Td88=
  on:
    tags: true
    branch: production
  skip_cleanup: true
